### ISSUE TITLE
Add flags for osx when _not_ crosscompiling

### ISSUE THREAD

**Issue by wolfv** [conda-forge/rust-activation-feedstock#65]
I think it's easy to overlink currently - because we are not setting the RUSTFLAGS on OSX when not cross-compiling. I think we should always set them ...

**Comment by hadim** [comment]
When running `pixi` compiled from https://github.com/prefix-dev/pixi and using the rust toolchain from conda-forge, I got the below error message on `osx-arm64`:

```
pixi/examples/flask-hello-world on  main [?⇡] via 🐍 v3.13.0 on ☁️   
❯ ../../target-pixi/release/pixi build
dyld[98511]: Library not loaded: @rpath/liblzma.5.dylib
  Referenced from: <E86679E3-7383-3039-9E4A-031C60A071A5> /Users/hadim/Code/libs/pixi/pixi/target-pixi/release/pixi
  Reason: no LC_RPATH's found
zsh: abort      ../../target-pixi/release/pixi build
```

After confirming, other users have the same issue when using an `osx-arm64` machine.

@wolfv proposed a fixed by tweaking the activation script of the build env on the pixi repo:

```
# on macOS we need to set these rust flags
export CARGO_TARGET_X86_64_APPLE_DARWIN_RUSTFLAGS="-C link-arg=-Wl,-rpath,$CONDA_PREFIX/lib"
export CARGO_TARGET_AARCH64_APPLE_DARWIN_RUSTFLAGS="-C link-arg=-Wl,-rpath,$CONDA_PREFIX/lib"
```

The fix works well for me and the question is whether we should backport that fix in this repo? I guess it might have unwanted side effects , so asking the @conda-forge/rust team whether they think it's a good idea or not.

**Comment by hadim** [comment]
(note that we could also apply that fix on the pixi repo directly, but it's not ideal since the issue also happens on other repos such as `rattler-build` for example)

**Comment by xhochy** [comment]
Yes, please make a PR to add this. I have came around a similar situation in some other package recently and made a similar fix in the feedstock there.

**Comment by hadim** [comment]
I opened a PR at https://github.com/conda-forge/rust-activation-feedstock/pull/67
